# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
#sudo: required
cache: packages

env:
  - GCAMDATA_USE_JAVA=TRUE

r_github_packages:
  - jimhester/covr
  - krlmlr/mockr
after_success:
  - time Rscript -e 'library(covr); package_coverage(function_exclusions="atest")'
  - time Rscript -e 'library(covr); codecov(function_exclusions = "atest")'
