# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
#sudo: required
cache: packages

env:
  - GCAMDATA_USE_JAVA=TRUE

r_github_packages:
  - jimhester/covr
  - krlmlr/mockr
after_success:
  - time Rscript -e 'library(covr); x <- package_coverage(function_exclusions="atest"); cat("coverage = ", percent_coverage(x), " %\\n"); save(x, file="x.dat")'
  - time Rscript -e 'library(covr); load("x.dat"); codecov(coverage=x)'
