# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
warnings_are_errors: true
cache: packages

before_install:
  - sudo fallocate -l 8g /mnt/for_fork.swap
  - sudo chmod 600 /mnt/for_fork.swap
  - sudo mkswap /mnt/for_fork.swap
  - sudo swapon /mnt/for_fork.swap

env:
  - GCAMDATA_USE_JAVA=TRUE

r_github_packages:
  - jimhester/covr@adffd69

script:
  - R CMD build .
  - travis_wait 30 R CMD check *.tar.gz

after_success:
  - travis_wait 30 Rscript coverage.R
