#' module_gcam.china_LB123.Electricity
#'
#' To be added.
#'
#' @param command API command to execute
#' @param ... other optional parameters, depending on command
#' @return Depends on \code{command}: either a vector of required inputs,
#' a vector of output names, or (if \code{command} is "MAKE") all
#' the generated outputs: \code{L123.in_EJ_province_elec_F}, \code{L123.out_EJ_province_elec_F}, \code{L123.in_EJ_province_ownuse_elec}, \code{L123.out_EJ_province_ownuse_elec}. The corresponding file in the
#' original data system was \code{LB123.Electricity.R} (gcam-china level1).
#' @details To be addeed.
#' @importFrom assertthat assert_that
#' @importFrom dplyr filter mutate select
#' @importFrom tidyr gather spread
#' @author Liu August 2018
module_gcam.china_LB123.Electricity <- function(command, ...) {
  if(command == driver.DECLARE_INPUTS) {
    return(c(FILE = "gcam-china/CPSY_GWh_province_F_elec_out",
             FILE = "gcam-china/province_names_mappings",
             "L123.in_EJ_R_elec_F_Yh",
             "L123.out_EJ_R_elec_F_Yh",
             "L126.in_EJ_R_elecownuse_F_Yh",
             "L126.out_EJ_R_elecownuse_F_Yh",
             "L101.inNBS_Mtce_province_S_F",
             "L132.out_EJ_province_indchp_F"))
  } else if(command == driver.DECLARE_OUTPUTS) {
    return(c("L123.in_EJ_province_elec_F",
             "L123.out_EJ_province_elec_F",
             "L123.in_EJ_province_ownuse_elec",
             "L123.out_EJ_province_ownuse_elec"))
  } else if(command == driver.MAKE) {

    fuel  <- CSP  <- sector <- scaler <-
      province.nam <- province <- Centralized.PV <- NULL     # silence package check.

    all_data <- list(...)[[1]]
    # -----------------------------------------------------------------------------
    # 1.Load required inputs
    province_names_mappings     <- get_data(all_data, "gcam-china/province_names_mappings")
    CPSY_GWh_province_F_elec_out <- get_data(all_data, "gcam-china/solar_csp_pv_capacityfactor")

    # -----------------------------------------------------------------------------
    # 2.perform computations



    # ===================================================
    L123.in_EJ_province_elec_F %>%
      add_title("Solar PV capacity factor adjustment by province") %>%
      add_units("Unitless") %>%
      add_comments("The scalars are generated by dividing data on capacity factors by province by national average capacity factor") %>%
      add_legacy_name("L123.in_EJ_province_elec_F") %>%
      add_precursors("gcam-china/province_names_mappings",
                     "gcam-china/CPSY_GWh_province_F_elec_out",
                     "L123.in_EJ_R_elec_F_Yh",
                     "L123.out_EJ_R_elec_F_Yh",
                     "L126.in_EJ_R_elecownuse_F_Yh",
                     "L126.out_EJ_R_elecownuse_F_Yh",
                     "L101.inNBS_Mtce_province_S_F",
                     "L132.out_EJ_province_indchp_F") ->
      L123.in_EJ_province_elec_F

    L123.out_EJ_province_elec_F %>%
      add_title("Solar PV capacity factor adjustment by province") %>%
      add_units("Unitless") %>%
      add_comments("The scalars are generated by dividing data on capacity factors by province by national average capacity factor") %>%
      add_legacy_name("L123.out_EJ_province_elec_F") %>%
      add_precursors("gcam-china/province_names_mappings",
                     "gcam-china/CPSY_GWh_province_F_elec_out",
                     "L123.in_EJ_R_elec_F_Yh",
                     "L123.out_EJ_R_elec_F_Yh",
                     "L126.in_EJ_R_elecownuse_F_Yh",
                     "L126.out_EJ_R_elecownuse_F_Yh",
                     "L101.inNBS_Mtce_province_S_F",
                     "L132.out_EJ_province_indchp_F") ->
      L123.out_EJ_province_elec_F

    L123.in_EJ_province_ownuse_elec %>%
      add_title("Solar PV capacity factor adjustment by province") %>%
      add_units("Unitless") %>%
      add_comments("The scalars are generated by dividing data on capacity factors by province by national average capacity factor") %>%
      add_legacy_name("L123.in_EJ_province_ownuse_elec") %>%
      add_precursors("gcam-china/province_names_mappings",
                     "gcam-china/CPSY_GWh_province_F_elec_out",
                     "L123.in_EJ_R_elec_F_Yh",
                     "L123.out_EJ_R_elec_F_Yh",
                     "L126.in_EJ_R_elecownuse_F_Yh",
                     "L126.out_EJ_R_elecownuse_F_Yh",
                     "L101.inNBS_Mtce_province_S_F",
                     "L132.out_EJ_province_indchp_F") ->
      L123.in_EJ_province_elec_F

    L123.out_EJ_province_ownuse_elec %>%
      add_title("Solar PV capacity factor adjustment by province") %>%
      add_units("Unitless") %>%
      add_comments("The scalars are generated by dividing data on capacity factors by province by national average capacity factor") %>%
      add_legacy_name("L123.out_EJ_province_ownuse_elec") %>%
      add_precursors("gcam-china/province_names_mappings",
                     "gcam-china/CPSY_GWh_province_F_elec_out",
                     "L123.in_EJ_R_elec_F_Yh",
                     "L123.out_EJ_R_elec_F_Yh",
                     "L126.in_EJ_R_elecownuse_F_Yh",
                     "L126.out_EJ_R_elecownuse_F_Yh",
                     "L101.inNBS_Mtce_province_S_F",
                     "L132.out_EJ_province_indchp_F") ->
      L123.out_EJ_province_ownuse_elec

    return_data(L123.in_EJ_province_elec_F, L123.out_EJ_province_elec_F, L123.in_EJ_province_ownuse_elec, L123.out_EJ_province_ownuse_elec)
  } else {
    stop("Unknown command")
  }
}
